GET https://www.qa.mvnctl.net/api/v1/_/metadata
Accept: application/json


###
POST https://www.qa.mvnctl.net/api/v1/api_key
Content-Type: application/json
Accept: application/json
User-Agent: MAVEN_ANDROID
x-Maven-Client: MAVEN_ANDROID/20111

{
  "email":"test+mvnqapreg03@mavenclinic.com",
  "password":"simpleisawesome1*"
}
###

GET https://www.qa.mvnctl.net/api/v1/users/57/dashboard
api-key: 41b18e24-ef0a-4be4-978f-82fac756e19b
Content-Type: application/json
Accept: application/json
User-Agent: MAVEN_ANDROID
x-Maven-Client: MAVEN_ANDROID/20111

###

GET https://www.qa.mvnctl.net/api/dashboard/
api-key: 41b18e24-ef0a-4be4-978f-82fac756e19b
Content-Type: application/json
Accept: application/json
User-Agent: MAVEN_ANDROID
x-Maven-Client: MAVEN_ANDROID/20111

###

GET https://www.qa.mvnctl.net/api/dashboard/pregnancy-week-28/
api-key: 41b18e24-ef0a-4be4-978f-82fac756e19b
Content-Type: application/json
Accept: application/json
User-Agent: MAVEN_ANDROID
x-Maven-Client: MAVEN_ANDROID/20111

###

GET https://www.qa.mvnctl.net/api/v1/me?include_profile=true
api-key:4e7815c7-c2c2-4d2b-bab1-2b16ba2ae252
Content-Type: application/json
Accept: application/json
User-Agent: MAVEN_ANDROID
x-Maven-Client: MAVEN_ANDROID/20111

###
